/** Local calendar dates are deliberately distinct from UTC timestamps. */
export const dayKey=(at:number)=>{const d=new Date(at);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export type Action='feed'|'walk'|'play'|'brush'|'bath'|'train'|'clean'|'health';
export const careConfig={hungerPerHour:2,moodPerHour:0.5,experiencePerLevel:100,maxLevel:20,snacksPerDay:3,windowMinutes:60,effects:{feed:[40,2,2,5,5],walk:[-5,20,10,20,15],play:[0,15,5,10,8],brush:[0,5,4,8,8],bath:[0,5,4,8,8],train:[0,8,4,8,8],clean:[0,5,4,8,8],health:[0,5,4,8,8]} as Record<Action,number[]>};
export const snacks=[{id:'biscuit',name:'小饼干',price:10,effect:[5,4,2]},{id:'chicken',name:'鸡肉干',price:20,effect:[8,8,4]},{id:'beef',name:'牛肉粒',price:25,effect:[10,7,5]},{id:'chew',name:'磨牙棒',price:30,effect:[6,10,5]},{id:'cheese',name:'奶酪块',price:35,effect:[8,12,6]}];
export type Task={id:string;day:string;kind:Action;title:string;scheduled:number|null;weekEnd?:string;actualSeconds?:number;actualSteps?:number;completedAt?:number;result?:'on-time'|'late';minutes?:number;steps?:number};
export type CareState={version:1;updatedAt:number;hunger:number;mood:number;intimacy:number;xp:number;coins:number;inventory:Record<string,number>;snackDays:Record<string,number>;tasks:Task[];ledger:{id:string;at:number;coins:number;note:string}[]};
export const initialCare=(at=Date.now(),intimacy=0):CareState=>({version:1,updatedAt:at,hunger:80,mood:100,intimacy,xp:0,coins:0,inventory:{},snackDays:{},tasks:[],ledger:[]});
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export function reconcile(c:CareState,at:number):CareState{const elapsed=Math.max(0,at-c.updatedAt)/3600000;return {...c,updatedAt:Math.max(c.updatedAt,at),hunger:clamp(c.hunger-elapsed*careConfig.hungerPerHour),mood:clamp(c.mood-elapsed*careConfig.moodPerHour)}}
export const growth=(xp:number)=>{const level=Math.min(careConfig.maxLevel,1+Math.floor(xp/careConfig.experiencePerLevel));return {level,stage:level<=5?'幼犬期':level<=15?'成长期':'成年期',progress:level===20?100:xp%careConfig.experiencePerLevel}};
export const hungerLabel=(v:number)=>v>=80?'吃得饱饱的':v>=50?'状态不错':v>=20?'有点饿啦':'肚子咕咕叫';
export const moodLabel=(v:number)=>v>=80?'开心':v>=50?'平静':v>=20?'有点无聊':'没什么精神';
export function dailyTasks(day:string,mode:string,times:Record<string,string>):Task[]{const defs:[string,Action,string][]=[['breakfast','feed','早餐'],...(mode==='trial'?[['morning','walk','早间遛狗'] as [string,Action,string]]:[]),['dinner','feed','晚餐'],['evening','walk',mode==='trial'?'晚间遛狗':'每日遛狗'],['play','play','陪它玩一会']];return defs.map(([key,kind,title])=>({id:`${day}:${mode}:${key}`,day,kind,title,scheduled:key==='play'?null:new Date(`${day}T${times[key]||'19:00'}:00`).getTime(),...(kind==='walk'?{minutes:key==='morning'?15:20,steps:key==='morning'?1000:1500}:{})}))}
export function ensureDay(c:CareState,mode:string,times:Record<string,string>,at:number){const state=reconcile(c,at),day=dayKey(at);if(state.tasks.some(t=>t.day===day&&t.id.includes(`:${mode}:`)))return state;return {...state,tasks:[...state.tasks,...dailyTasks(day,mode,times)]}}
export function taskStatus(t:Task,at:number){if(t.completedAt)return t.result==='late'?'延迟完成':'准时完成';if((t.weekEnd||t.day)<dayKey(at))return '未完成';if(t.day>dayKey(at))return '未开始';if(t.scheduled&&!(t.kind==='walk'&&t.id.includes(':companion:'))&&at<t.scheduled-(t.id.includes(':companion:')?180:careConfig.windowMinutes)*60000)return '未开始';return '可执行'}
export function completeTask(c:CareState,id:string,at:number,walk?:{seconds:number;steps:number;verified:boolean}):CareState{const task=c.tasks.find(t=>t.id===id);if(!task||task.completedAt||(task.day>dayKey(at)||(task.weekEnd||task.day)<dayKey(at))||taskStatus(task,at)==='未开始')return c;if(task.kind==='walk'&&(!walk?.verified||walk.seconds<(task.minutes||20)*60||walk.steps<(task.steps||1500)))return c;const state=reconcile(c,at),[h,m,i,x,coins]=careConfig.effects[task.kind];return {...state,hunger:clamp(state.hunger+h),mood:clamp(state.mood+m),intimacy:state.intimacy+i,xp:state.xp+x,coins:state.coins+coins,tasks:state.tasks.map(t=>t.id===id?{...t,completedAt:at,...(walk?{actualSeconds:walk.seconds,actualSteps:walk.steps}:{}),result:task.scheduled&&at>task.scheduled+careConfig.windowMinutes*60000?'late':'on-time'}:t),ledger:[...state.ledger,{id,at,coins,note:task.title}]}}
export function buySnack(c:CareState,id:string,at:number,transactionId:string){const snack=snacks.find(s=>s.id===id);if(!snack||c.coins<snack.price||c.ledger.some(l=>l.id===transactionId))return c;return {...c,coins:c.coins-snack.price,inventory:{...c.inventory,[id]:(c.inventory[id]||0)+1},ledger:[...c.ledger,{id:transactionId,at,coins:-snack.price,note:`购买${snack.name}`}]}}
export function feedSnack(c:CareState,id:string,at:number){const snack=snacks.find(s=>s.id===id),day=dayKey(at);if(!snack||!c.inventory[id]||(c.snackDays[day]||0)>=careConfig.snacksPerDay)return c;const state=reconcile(c,at);return {...state,hunger:clamp(state.hunger+snack.effect[0]),mood:clamp(state.mood+snack.effect[1]),intimacy:state.intimacy+snack.effect[2],inventory:{...state.inventory,[id]:state.inventory[id]-1},snackDays:{...state.snackDays,[day]:(state.snackDays[day]||0)+1}}}

export function bonuses(c:CareState,mode:string,at:number,scope=''):CareState{let state=c;const source=c.tasks.filter(t=>!t.weekEnd&&(mode==='companion'?t.id.includes(':companion:'):!scope||t.id.startsWith(scope+':')));const days=[...new Set(source.map(t=>t.day))].sort();let streak=0,previous='';for(const day of days){const tasks=source.filter(t=>t.day===day);const d=new Date(day+'T12:00:00');d.setDate(d.getDate()-1);if(previous!==dayKey(d.getTime()))streak=0;previous=day;if(tasks.length!==(mode==='trial'?5:4)||!tasks.every(t=>t.completedAt)){streak=0;continue}streak++;const id='daily:'+tasks[0].id.split(':').slice(0,-1).join(':');if(!state.ledger.some(l=>l.id===id)){const trial=mode==='trial';state={...state,xp:state.xp+(trial?40:30),intimacy:state.intimacy+(trial?20:15),coins:state.coins+(trial?40:30),ledger:[...state.ledger,{id,at,coins:trial?40:30,note:'每日完整照顾奖励'}]}}if(mode==='trial'&&[3,7,14].includes(streak)){const id='streak:'+tasks[0].id;const coins=streak===3?30:streak===7?80:150;if(!state.ledger.some(l=>l.id===id))state={...state,coins:state.coins+coins,ledger:[...state.ledger,{id,at,coins,note:'连续照顾奖励'}]}}}return state}

/** Inclusive calendar days since adoption; independent of mode and DST. */
export function companionshipDays(created:string|undefined,at=Date.now()):number{const start=created?.slice(0,10);if(!start||!/^\d{4}-\d{2}-\d{2}$/.test(start))return 1;const date=Date.parse(start+'T00:00:00Z'),now=Date.parse(dayKey(at)+'T00:00:00Z');return Number.isFinite(date)?Math.max(1,Math.floor((now-date)/86400000)+1):1}
