import {dayKey,dailyTasks,type Task} from './engine';
export const shiftDay=(day:string,n:number)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return dayKey(d.getTime())};
export type Goal={minutes:number;steps:number};
export type Adjustment={at:number;target:string;before:Goal;after:Goal;reason:string};
export type Cycle={id:string;start:string;end:string;status:'active'|'complete'|'exited';endedAt?:number;tasks:Task[];adjustments:Adjustment[];times:Record<string,string>;goals:Record<string,Goal>;demo?:boolean};
export const quotas={brush:2,train:2,bath:1,clean:1,health:1};
export const careNames={brush:'梳毛',train:'训练',bath:'洗澡',clean:'清洁狗窝',health:'健康检查'};
export function newCycle(at:number,times:Record<string,string>):Cycle{const start=dayKey(at);return {id:crypto.randomUUID(),start,end:shiftDay(start,29),status:'active',tasks:[],adjustments:[],times:{...times},goals:{morning:{minutes:15,steps:1000},evening:{minutes:20,steps:1500}}}}
export function cycleTasks(c:Cycle,at:number):Cycle{const last=dayKey(at)>c.end?c.end:dayKey(at);let tasks=[...c.tasks];for(let day=c.start;day<=last;day=shiftDay(day,1)){if(!tasks.some(t=>t.day===day&&!t.weekEnd)){tasks.push(...dailyTasks(day,'trial',c.times).map(t=>{const goal=c.goals[t.id.endsWith('morning')?'morning':'evening'];return {...t,id:c.id+':'+t.id,...(t.kind==='walk'?goal:{})}}))}}
for(let i=0;i<30;i+=7){const start=shiftDay(c.start,i);if(start>last)break;const end=shiftDay(c.start,Math.min(i+6,29));for(const [kind,amount] of Object.entries(quotas)){for(let j=0;j<amount;j++){const id=`${c.id}:week${i}:${kind}:${j}`;if(!tasks.some(t=>t.id===id))tasks.push({id,day:start,weekEnd:end,kind:kind as Task['kind'],title:careNames[kind as keyof typeof careNames],scheduled:null})}}}
return {...c,tasks,status:c.status==='active'&&dayKey(at)>c.end?'complete':c.status}}
export function report(c:Cycle,at:number){const closed=c.status==='exited'?dayKey(c.endedAt||at):dayKey(at)>c.end?c.end:shiftDay(dayKey(at),-1);const daily=c.tasks.filter(t=>!t.weekEnd&&t.day<=closed&&!(c.status==='exited'&&!t.completedAt&&t.scheduled&&t.scheduled-3600000>(c.endedAt||at))),care=c.tasks.filter(t=>t.weekEnd&&t.weekEnd<=closed),done=(a:Task[])=>a.filter(t=>t.completedAt).length,rate=(a:Task[],predicate=(t:Task)=>!!t.completedAt)=>a.length?Math.round(a.filter(predicate).length/a.length*100):null;
const feeds=daily.filter(t=>t.kind==='feed'),walks=daily.filter(t=>t.kind==='walk'),play=daily.filter(t=>t.kind==='play');const days=[...new Set(daily.map(t=>t.day))].sort();let longest=0,current=0,full=0;for(const day of days){const ts=daily.filter(t=>t.day===day);if(ts.length===5&&ts.every(t=>t.completedAt)){full++;current++;longest=Math.max(longest,current)}else current=0}
const weekday=daily.filter(t=>![0,6].includes(new Date(t.day+'T12:00:00').getDay())),weekend=daily.filter(t=>!weekday.includes(t));const feedback:string[]=[];if(days.length<7)feedback.push('记录还不满一周，先慢慢建立日常，暂不推断生活规律。');else {const am=rate(walks.filter(t=>t.id.endsWith('morning'))),pm=rate(walks.filter(t=>t.id.endsWith('evening')));if(am!==null&&pm!==null&&am!==pm)feedback.push(am>pm?'早间遛狗比晚间更容易完成，可以留意晚间的时间安排。':'晚间遛狗比早间更容易完成，可以留意早间的时间安排。');if(weekday.length&&weekend.length&&rate(weekend)!>rate(weekday)!)feedback.push('周末的任务完成率高于工作日，工作日的照顾安排值得继续观察。');if((rate(feeds,t=>t.result==='on-time')||0)>=80)feedback.push('固定时间喂食是你目前较稳定的日常。');if((rate(care)||0)>=80)feedback.push('你较稳定地完成了周期护理。');if(c.adjustments.length)feedback.push('你曾主动调整目标，让照顾安排更贴近自己的生活。');if(!feedback.length)feedback.push('不同任务的完成情况已有记录，可以从最容易安排的一项开始建立规律。')}
if(days.length>=7){feedback.push(`本期已统计 ${days.length} 天，其中 ${full} 天完成了全部每日任务。`);feedback.push(`已记录 ${done(care)} 次护理，可以继续留意每周的照顾安排。`)}
return {days:days.length,full,longest,current,feeding:rate(feeds,t=>t.result==='on-time'),feedingLate:rate(feeds,t=>t.result==='late'),feedingMissed:rate(feeds,t=>!t.completedAt),walking:rate(walks),morning:rate(walks.filter(t=>t.id.endsWith('morning'))),evening:rate(walks.filter(t=>t.id.endsWith('evening'))),play:rate(play),care:rate(care),totalRate:rate([...daily,...care]),walkCount:done(walks),steps:walks.reduce((n,t)=>n+(t.actualSteps||0),0),minutes:Math.round(walks.reduce((n,t)=>n+(t.actualSeconds||0),0)/60),careCount:done(c.tasks.filter(t=>t.weekEnd&&t.day<=closed)),feedback:feedback.slice(0,5),daysList:days.map(day=>({day,complete:daily.filter(t=>t.day===day).length===5&&daily.filter(t=>t.day===day).every(t=>t.completedAt)}))}}
export function demoCycles(at:number,times:Record<string,string>){return [60,30].map((ago,idx)=>{const c=newCycle(new Date(shiftDay(dayKey(at),-ago)+'T00:00:00').getTime(),times);let result=cycleTasks(c,at);result={...result,demo:true,tasks:result.tasks.map((t,i)=>i%(idx?7:5)===0?t:{...t,completedAt:(t.scheduled||new Date(t.day+'T12:00:00').getTime())+(i%9===0?7200000:0),result:i%9===0?'late':'on-time',...(t.kind==='walk'?{actualSteps:(t.steps||0)+80,actualSeconds:(t.minutes||0)*60+60}:{})})};return result})}
